server: 
    port: 8087
    
spring:
    jpa: 
        properties: 
            hibernate: 
                dialect: org.hibernate.dialect.MySQLDialect
        hibernate: 
            ddl-auto: none
    datasource: 
        url: jdbc:mysql://localhost:3306/our_spring_boot_app?useSSL=false 
        username: root
        password: root
        driverClassName: com.mysql.cj.jdbc.Driver
         
         